### PR TITLE
API calls made to be lowercase

### PR DESCRIPTION
**Pull request by masonitea**

### CODE REVIEW

**Comment by jiejasonliu** [comment]
this is great! does case-sensitivity matter for `/Refresh` as well?
if so, you may need to do the same for `use-fetch-wrapper:164`

otherwise, LGTM!

**Comment by masonitea** [comment]
I believe I changed that line. Prior to this though /Refresh and /Authenticate were being called when the endpoints were /refresh and /authenticate already. IDK if it would without these changes with the backend being changed but this is just for the sake of consistency.
joebiden

**Comment by jiejasonliu** [comment]
oh wth i'm blind!!! 👀 
but yeah, maybe it's not case-sensitive, but for consistency sake this is definitely better!

**Review by jiejasonliu — APPROVED** [review]

**Review by derricklee43 — APPROVED** [review]
lgtm!

**Pull request merged**
